name: AQRE CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (fast LOO on CI)
        shell: pwsh
        env:
          PYTHONUTF8: "1"
          AQRE_LOO_CALIBRATE: "0"   # CI'da kalibrasyon kapalı (hız)
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          Write-Host "Script: $pwd\tools\aqre_pipeline.ps1"
          ./tools/aqre_pipeline.ps1

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports
          path: |
            reports/loo_summary.json
            reports/loo_predictions.csv
            reports/metrics.json
          if-no-files-found: warn

      - name: Upload models
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: models
          path: |
            models/*.joblib
          if-no-files-found: warn
