name: AQRE CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: windows-latest
    env:
      PYTHONUTF8: "1"
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pipeline (fresh data on clean runner)
        shell: pwsh
        run: |
          Set-ExecutionPolicy Bypass -Scope Process -Force
          ./tools/aqre_pipeline.ps1 -Rebuild

      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            reports/loo_summary.json
            reports/loo_predictions.csv
            reports/metrics.json
          if-no-files-found: ignore

      - name: Upload models
        uses: actions/upload-artifact@v4
        with:
          name: models
          path: models/*.joblib
          if-no-files-found: ignore
